//
//  AppStrings.swift
//  playground
//
//  Centralized translation model for all app strings
//

import Foundation

/// Centralized model for all app strings
/// All strings should be defined here and accessed through this model
struct AppStrings {
    
    // MARK: - Common
    struct Common {
        static let save = "Save"
        static let cancel = "Cancel"
        static let done = "Done"
        static let delete = "Delete"
        static let edit = "Edit"
        static let ok = "OK"
        static let yes = "Yes"
        static let no = "No"
        static let close = "Close"
        static let back = "Back"
        static let next = "Next"
        static let previous = "Previous"
        static let settings = "Settings"
        static let skip = "Skip"
        static let signIn = "Sign In"
        static let continue_ = "Continue"
        static let finish = "Finish"
        static let loading = "Loading..."
        static let error = "Error"
        static let errorOccurred = "An error occurred"
        static let errorColon = "Error: %@"
        static let success = "Success"
        static let retry = "Retry"
        static let somethingWentWrong = "Something went wrong"
        static let tryAgain = "Try Again"
        static let dismiss = "Dismiss"
        static let dismissKeyboard = "Dismiss keyboard"
        static let untitled = "Untitled"
        static let unlock = "Unlock"
        static let exportAsCSV = "Export as CSV"
        static let logIn = "Log In"
        static let openSettings = "Open Settings"
        static let remove = "Remove"
        static let optional = "Optional"
        static let tapToViewDetails = "Tap to view details for this day"
        static let enabled = "Enabled"
        static let readMore = "Read More"
        static let showLess = "Show Less"
        static let actions = "Actions"
        static let send = "Send"
    }
    
    // MARK: - Home
    struct Home {
        static let title = "Home"
        static let macronutrients = "Macronutrients"
        static let recentlyUploaded = "Recently uploaded"
        static let caloriesLeft = "Calories left"
        static let gained = "Gained"
        static let lost = "Lost"
        static let net = "Net"
        static let consumed = "Consumed"
        static let burned = "Burned"
        static let noMealsYet = "No meals yet"
        static let tapToAddFirstMeal = "Tap + to add your first meal of the day"
        static let myBadges = "My Badges"
        static let more = "more"
        static let tapToViewBadges = "Tap to view all badges and achievements"
        static let viewAll = "View All"
        static let today = "Today"
        static let yesterday = "Yesterday"
        static let over = "over"
        static let scanFood = "Scan food"
        static let saveExercise = "Save exercise"
        static let todaysDietPlan = "Today's Diet Plan"
        static let summary = "Summary"
        static let previous = "Previous:"
        static let next_ = "Next:"
        static let nextBadge = "Next: %@"
        static let goalLabel = "Goal:"
        static let saveItems = "Save %d Item%@"
        static let saveItem = "Save Item"
        static let saveItemsPlural = "Save Items"
        static let healthKitUnavailable = "HealthKit Unavailable"
        static let healthDataNotAvailable = "Health data is not available on this device"
        static let connectHealth = "Connect Health"
        static let viewDailyActivity = "View your daily activity and exercise data"
        static let enableHealthAccess = "Continue"
        static let protein = "Protein"
        static let calories = "Calories"
        static let carbs = "Carbs"
        static let fat = "Fat"
        static let proteinShort = "P"
        static let carbsShort = "C"
        static let fatShort = "F"
        static let delete = "Delete"
    }
    
    // MARK: - Progress
    struct Progress {
        static let title = "Progress"
        static let loadingProgressData = "Loading progress data..."
        static let currentWeight = "Current Weight"
        static let weightChanges = "Weight Changes"
        static let overDifferentPeriods = "Over different periods"
        static let progressPhotos = "Progress Photos"
        static let dailyAverageCalories = "Daily Average Calories"
        static let todayTrend = "Today's Trend"
        static let noDataToday = "No data for today"
        static let bmi = "BMI"
        static let healthKit = "HealthKit"
        static let saveWeight = "Save Weight"
        static let logWeight = "Log Weight"
        static let viewProgress = "View Progress"
        static let threeDay = "3 day"
        static let sevenDay = "7 day"
        static let fourteenDay = "14 day"
        static let thirtyDay = "30 day"
        static let ninetyDay = "90 day"
        static let allTime = "All Time"
        static let last7Days = "Last 7 Days"
        static let last2Weeks = "Last 2 Weeks"
        static let last3Weeks = "Last 3 Weeks"
        static let lastMonth = "Last Month"
        static let last3Months = "Last 3 Months"
        static let last6Months = "Last 6 Months"
        static let lastYear = "Last Year"
        static let daysCapitalized = "Days"
        static let totalCal = "Total Cal"
        static let avgPerDay = "Avg/Day"
        static let avgMacro = "avg %@"
        static let gained_ = "Gained"
        static let lost_ = "Lost"
        static let noChange = "No change"
        static let saveWeightButton = "Save weight"
        static let start = "Start"
        static let goal = "Goal"
        static let startWeightWithUnit = "Start: %.1f %@"
        static let goalWeightWithUnit = "Goal: %.1f %@"
        static let weightWithUnit = "%.1f %@"
        static let bodyMassIndex = "Body Mass Index"
        static let cal = "cal"
        static let goalLabel = "Goal"
        static let viewDailyBreakdown = "View Daily Breakdown"
        static let healthData = "Health Data"
        static let healthAccessRequired = "Health Access Required"
        static let goToSettings = "Go to Settings > Privacy & Security > Health > CalorieVisionAI"
        static let openSettings = "Open Settings"
        static let steps = "Steps"
        static let activeCalories = "Active Calories"
        static let exercise = "Exercise"
        static let heartRate = "Heart Rate"
        static let distance = "Distance"
        static let sleep = "Sleep"
        static let weightProgress = "Weight Progress"
        static let current = "Current"
        static let change = "Change"
        static let weightTrend = "Weight Trend"
        static let noWeightData = "No Weight Data"
        static let saveWeightToSeeProgress = "Save your weight to see progress over time"
        static let history = "History"
        static let entries = "entries"
        static let entriesWithCount = "%d entries"
        static let noEntriesYet = "No entries yet"
        static let caloriesBreakdown = "Calories Breakdown"
        static let dailyAverage = "Daily Average"
        static let duration = "Duration"
        static let previousWeight = "Previous: %@ %@"
        static let daysTracked = "days tracked"
        static let average = "Average"
        static let lowest = "Lowest"
        static let highest = "Highest"
        static let entriesLabel = "Entries"
        static let calorieTrend = "Calorie Trend"
        static let noCalorieData = "No Calorie Data"
        static let startTrackingMeals = "Start tracking meals to see your calorie trends"
        static let dailyBreakdown = "Daily Breakdown"
        static let days = "days"
        static let avg = "avg"
        static let saveYourWeight = "Save Your Weight"
        static let trackProgressBySaving = "Track your progress by saving your current weight"
        static let total = "Total"
        static let weightChart = "Weight Chart"
        static let stableThisPeriod = "Stable this period"
        static let now = "Now"
    }
    
    // MARK: - Food & Meals
    struct Food {
        static let saveFood = "Save Food"
        static let logFood = "Log Food"
        static let foodSaved = "Food saved successfully!"
        static let foodSavedSuccessfully = "Food saved successfully!"
        static let saveMeal = "Save Meal"
        static let describe = "Describe"
        static let scan = "Scan"
        static let exercise = "Exercise"
        static let diet = "Diet"
        static let todayActivity = "Today's Activity"
        static let viewAll = "View All"
        static let meals = "Meals"
        static let workouts = "Workouts"
        static let noLogsYet = "No Logs Yet"
        static let startLogging = "Start logging your meals and exercises to see them here"
        static let noActivityYet = "No Activity Yet"
        static let startSaving = "Start saving your meals and exercises to see them here"
        static let quickSave = "Quick Save"
        static let whatDidYouEat = "What did you eat?"
        static let estimatedCalories = "Estimated Calories"
        static let kcal = "kcal"
        static let quickPresets = "Quick Presets"
        static let lightSnack = "Light Snack"
        static let smallMeal = "Small Meal"
        static let regularMeal = "Regular Meal"
        static let largeMeal = "Large Meal"
        static let category = "Category"
        static let whatExerciseDidYouDo = "What exercise did you do?"
        static let minutes = "minutes"
        static let caloriesBurned = "Calories Burned"
        static let savedSuccessfully = "Saved Successfully!"
        static let yourFoodHasBeenLogged = "Your food has been logged."
        static let yourExerciseHasBeenLogged = "Your exercise has been logged."
        static let describeYourFood = "Describe Your Food"
        static let tellUsWhatYouAte = "Tell us what you ate"
        static let describeMealNaturalLanguage = "Describe your meal in natural language and we'll calculate the nutrition for you"
        static let iHad = "I had..."
        static let trySaying = "Try saying:"
        static let mealCategory = "Meal Category"
        static let analyzeWithAI = "Analyze with AI"
        static let analyzingYourMeal = "Analyzing your meal..."
        static let usingAIToIdentify = "Using AI to identify ingredients and calculate nutrition"
        static let analysisComplete = "Analysis Complete"
        static let remove = "Remove"
        static let startOver = "Start Over"
        static let calBurned = "cal burned"
        static let voiceLog = "Voice Log"
        static let transcribed = "Transcribed:"
        static let comingSoon = "Coming Soon"
        static let listening = "Listening..."
        static let tapToStart = "Tap to start"
        static let describeWhatYouAte = "Describe what you ate"
        static let voiceLoggingWillBeAvailableSoon = "Voice logging will be available soon"
        static let stop = "Stop"
        static let startListening = "Start Listening"
        static let voiceLoggingInDevelopment = "Voice logging is currently in development. Soon you'll be able to describe your meals naturally and have them automatically logged."
        static let microphoneAccess = "Microphone Access"
        static let voiceLoggingRequiresMicrophone = "Voice logging requires microphone access. Please enable it in Settings to use this feature."
        static let recentlyUploaded = "Recently uploaded"
        static let delete = "Delete"
        static let saveToQuickAdd = "Save to Quick Add"
        static let saveToQuickAddDescription = "Save this food to your Quick Add list for easy access later"
        static let categoryColon = "Category:"
        static let analyzingYourFood = "Analyzing your food..."
        static let usingAIToIdentifyCalories = "Using AI to identify calories and nutrients"
        static let quickAdd = "Quick Add"
        static let commonFoods = "Common Foods"
        static let recentFoods = "Recent Foods"
        static let savedFoods = "Saved Foods"
        static let manual = "Manual"
        static let voice = "Voice"
        static let portion = "Portion"
        static let serving = "serving"
        static let gram = "g"
        static let ounce = "oz"
        static let cup = "cup"
        static let piece = "piece"
        static let all = "All"
        static let recent = "Recent"
        static let saved = "Saved"
        static let noRecentFoods = "No Recent Foods"
        static let noSavedFoods = "No Saved Foods"
        static let foodDetails = "Food Details"
        static let nutrition = "Nutrition"
        static let portionColon = "Portion:"
        static let manualEntry = "Manual Entry"
        static let confirmFoods = "Confirm Foods"
        static let identifiedFoods = "Identified Foods"
        static let searchOrDescribeFood = "Search or describe what you ate..."
        static let noFoodsFound = "No Foods Found"
        static let tryDifferentSearch = "Try a different search term or use AI to analyze your food"
        static let custom = "Custom"
        static let recentFoodsWillAppear = "Foods you log will appear here for quick access"
        static let tapBookmarkToSave = "Tap the bookmark icon on any food to save it here"
        static let searchOrCreate = "Search foods or create custom entry"
        static let quickSaveDescription = "Quickly log with calorie estimate"
        static let textLog = "Text Log"
        static let textLogDescription = "Describe your meal in words"
    }
    
    // MARK: - Exercise
    struct Exercise {
        static let saveExercise = "Save Exercise"
        static let logExercise = "Log Exercise"
        static let exerciseSaved = "Exercise saved successfully!"
        static let selectType = "Select Exercise Type"
        static let duration = "Duration"
        static let intensity = "Intensity"
        static let calories = "Calories"
        static let describeExercise = "Describe Exercise"
        static let manualEntry = "Manual Entry"
        static let yourWorkoutBurned = "Your workout burned"
        static let cals = "Cals"
        static let burnedCalories = "Burned Calories"
        static let saving = "Saving..."
        static let describeYourWorkout = "Describe your workout"
        static let durationMinutes = "Duration (minutes)"
        static let enterCaloriesBurned = "Enter calories burned"
        static let setIntensity = "Set intensity"
        static let mins = "mins"
        static let high = "High"
        static let sprinting = "Sprinting - 14 mph (4 minute miles)"
        static let medium = "Medium"
        static let jogging = "Jogging - 6 mph (10 minute miles)"
        static let low = "Low"
        static let walking = "Walking - 3 mph (20 minute miles)"
        static let walk = "Walk"
        static let run = "Run"
        static let weights = "Weights"
        static let cycling = "Cycling"
        static let weightLifting = "Weight Lifting"
        static let reps = "Reps"
        static let sets = "Sets"
        static let weight = "Weight"
        static let chillWalk = "Chill Walk"
        static let addSet = "Add Set"
        static let totalVolume = "Total Volume"
        static let pace = "Pace"
        static let distance = "Distance"
        static let totalReps = "Total Reps"
        static let setsXReps = "Sets x Reps"
        static let volume = "Volume"
        static let setNumber = "Set %d"
        static let weightWithUnit = "Weight (%@)"
    }
    
    // MARK: - Diet Plans
    struct DietPlan {
        static let title = "Diet Plan"
        static let myDiet = "My Diet"
        static let createDietPlan = "Create Diet Plan"
        static let editDietPlan = "Edit Diet Plan"
        static let deleteDietPlan = "Delete Diet Plan"
        static let noDietPlan = "No Diet Plan"
        static let createDietDescription = "Create a diet plan to schedule repetitive meals and track your adherence"
        static let todayDietPlan = "Today's Diet Plan"
        static let mealsCompleted = "meals completed"
        static let mealsCompletedFormat = "%d/%d meals completed"
        static let scheduledMeals = "Scheduled Meals"
        static let noMealsScheduled = "No meals scheduled"
        static let noMealsScheduledDescription = "No meals are scheduled for this day in your diet plan."
        static let addScheduledMeal = "Add Scheduled Meal"
        static let dailyCalorieGoal = "Daily Calorie Goal"
        static let calculatedMacros = "Calculated Macros"
        static let adherence = "Adherence"
        static let adherenceTrend = "Adherence Trend"
        static let todaySchedule = "Today's Schedule"
        static let insights = "Insights"
        static let weeklyStatistics = "Weekly Statistics"
        static let noDataAvailable = "No data available"
        static let offDietMeals = "Off-Diet Meals"
        static let caloriesFromOffDiet = "calories from off-diet meals"
        static let onlyOneActivePlan = "You can only have one active diet plan at a time. Creating a new plan will replace this one."
        static let addAtLeastOneMeal = "Please add at least one scheduled meal before saving the diet plan."
        static let noMealsAlert = "No Meals Scheduled"
        static let addMealsToDietPlan = "Add meals to your diet plan to see them here"
        static let goalNotMet = "Goal not met"
        static let calories = "calories"
        static let active = "Active"
        static let inactive = "Inactive"
        static let creatingNewPlanWillReplace = "Creating a new plan will replace your current active diet plan. You can only have one active diet plan at a time."
        static let useThisTemplate = "Use This Template"
        static let dietPlanTemplates = "Diet Plan Templates"
        static let templatePreview = "Template Preview"
        static let nameYourDietPlan = "Name Your Diet Plan"
        static let giveDietPlanName = "Give your diet plan a memorable name"
        static let chooseTemplateOptional = "Choose a Template (Optional)"
        static let startWithTemplate = "Start with a template or create from scratch"
        static let startFromScratch = "Start from Scratch"
        static let welcomeToDietPlans = "Welcome to Diet Plans!"
        static let createPersonalizedMealSchedules = "Create personalized meal schedules and track your adherence to reach your nutrition goals."
        static let smartReminders = "Smart Reminders"
        static let trackYourProgress = "Track Your Progress"
        static let monitorDietAdherence = "Monitor your diet adherence, see insights about your eating patterns, and stay on track with your nutrition goals."
        static let dailyAdherenceTracking = "Daily adherence tracking"
        static let weeklyProgressCharts = "Weekly progress charts"
        static let addNewFood = "Add New Food"
        static let personalizedInsights = "Personalized insights"
        static let streak = "Streak"
        static let bestDay = "Best Day"
        static let tip = "Tip"
        static let avgAdherence = "Avg Adherence"
        static let mealsCompletedCapitalized = "Meals Completed"
        static let timeRange = "Time Range"
        static let skip = "Skip"
        static let days = "days"
        static let notAvailable = "N/A"
        static let startTrackingForTips = "Start tracking to get personalized tips"
        static let trySettingReminders = "Try setting reminders 15 minutes before meal time"
        static let planAheadOffDiet = "Plan ahead to avoid off-diet meals"
        static let greatJobKeepConsistency = "Great job! Keep up the consistency"
        static let doingWellSmallImprovements = "You're doing well! Small improvements add up"
        static let today = "Today"
        static let thisWeek = "This Week"
        static let thisMonth = "This Month"
        static let allDays = "All Days"
        static let scanYourFood = "Scan Your Food"
        static let openCameraToScan = "This will open the camera to scan and analyze your food"
        static let saveMealAsPlanned = "Save Meal as Planned"
        static let editAndAddItems = "Edit & Add Items"
        static let expectedCalories = "Expected Calories"
        static let takePhotoToVerify = "Take a photo of your meal to verify it matches your planned calories"
        static let skipVerification = "Skip Verification"
        static let comparingCalories = "Comparing calories with your planned meal"
        static let saveAsPlanned = "Save as Planned"
        static let skipThisMeal = "Skip This Meal"
        static let plannedMeal = "Planned Meal"
        static let total = "Total"
        static let scanOrSelectPhoto = "Scan or select a photo to analyze your food"
        static let howWouldYouLikeToLog = "How would you like to log this meal?"
        static let repeatOn = "Repeat on:"
        static let selectAtLeastOneDay = "Select at least one day"
        static let dietInsights = "Diet Insights"
        static let startFollowingDietPlan = "Start following your diet plan to see insights"
        static let overallDietScore = "Overall Diet Score"
        static let completionByMealType = "Completion by Meal Type"
        static let timePatterns = "Time Patterns"
        static let personalizedRecommendations = "Personalized Recommendations"
        static let consistency = "Consistency"
        static let planning = "Planning"
        static let bestTime = "Best Time"
        static let mostChallengingDay = "Most Challenging Day"
        static let improvementTrend = "Improvement Trend"
        static let improveAdherence = "Improve Adherence"
        static let focusOnCategory = "Focus on %@"
        static let buildConsistency = "Build Consistency"
        static let keepItUp = "Keep It Up!"
        static let previewUnavailable = "Preview unavailable"
        static let timeForMeal = "Time for %@"
        static let analyzingYourMeal = "Analyzing your meal..."
        static let greatCaloriesMatch = "Great! Calories Match"
        static let closeMatch = "Close Match"
        static let caloriesDontMatch = "Calories Don't Match"
        static let expected = "Expected:"
        static let detected = "Detected:"
        static let difference = "Difference:"
        static let takeAnotherPhoto = "Take Another Photo"
        static let excellentDoingGreat = "Excellent! You're doing great"
        static let goodProgressKeepItUp = "Good progress, keep it up"
        static let roomForImprovement = "Room for improvement"
        static let letsGetBackOnTrack = "Let's get back on track"
        static let youAreMissing = "You're missing %@ meals. Consider adjusting your schedule."
        static let adherenceBelow70 = "Your adherence is below 70%. Try setting reminders 15 minutes before meal times."
        static let adherenceVaries = "Your adherence varies day-to-day. Try to maintain a regular meal schedule."
        static let doingGreatContinue = "You're doing great! Continue following your diet plan for best results."
        static let schedule = "Schedule"
        static let timeFor = "Time for %@"
        static let addFood = "Add Food"
        static let editMeal = "Edit Meal"
        static let mealReminder = "Meal Reminder"
        static let verifyMeal = "Verify Meal"
        static let mealDetails = "Meal Details"
        static let newScheduledMeal = "New Scheduled Meal"
        static let editScheduledMeal = "Edit Scheduled Meal"
        static let scheduleYourMeals = "Schedule Your Meals"
        static let reviewYourPlan = "Review Your Plan"
        static let planName = "Plan Name"
        static let planDetails = "Plan Details"
        static let descriptionOptional = "Description (optional)"
        static let totalMeals = "Total Meals"
        static let daysActive = "Days Active"
        static let stepXOfY = "Step %d of %d: %@"
        static let addYourFirstScheduledMeal = "Add your first scheduled meal"
        static let noInsightsAvailable = "No Insights Available"
        static let analyzingYourDiet = "Analyzing your diet..."
        static let updateMeal = "Scan or select a photo to update your meal"
        static let stepName = "Name"
        static let stepTemplate = "Template"
        static let stepMeals = "Meals"
        static let stepReview = "Review"
        static let mealName = "Meal Name"
        static let time = "Time"
        static let period = "Period"
        static let planNamePlaceholder = "e.g., Weight Loss Plan"
        static let completedOfScheduled = "%d/%d completed"
        static let morning = "Morning"
        static let afternoon = "Afternoon"
        static let evening = "Evening"
        static let improving = "Improving"
        static let declining = "Declining"
        static let stable = "Stable"
        static let insufficientData = "Insufficient data"
        static let difficultyEasy = "Easy"
        static let difficultyMedium = "Medium"
        static let difficultyAdvanced = "Advanced"
        static let replacingExisting = "Replacing Existing Plan"
        static let mealsRequired = "Meals Required"
        static let descriptionPlaceholder = "Brief description of your diet plan"
        static let perWeek = "Per Week"
        static let quickSetup = "Quick Setup"
        static let quickSetupDescription = "Create a plan in minutes"
        static let useTemplate = "Use Template"
        static let createFromScratch = "Create from Scratch"
        static let planSummary = "Plan Summary"
        static let todaysMeals = "Today's Meals"
        static let noMealsToday = "No meals scheduled for today"
        static let replaceWithTemplate = "Replace with Template"
        static let deleteConfirmation = "This will delete your diet plan and all scheduled meals. This action cannot be undone."
        static let activePlan = "Active Plan"
        static let savedPlans = "Saved Plans"
        static let createNewPlan = "Create New Plan"
        static let activate = "Activate"
        static let deactivate = "Deactivate"
        static let fromScratch = "Scratch"
        static let week = "week"
        static let switchPlan = "Switch Plan"
        static let currentPlan = "Current Plan"
        static let noPlanActive = "No Plan Active"
        static let noPlanActiveDescription = "You have saved diet plans but none are currently active. Activate a plan to start tracking your meals."
        static let activateAPlan = "Activate a Plan"
        static let savedPlansAvailable = "%d saved plan(s) available"
        static let tapToSelectPlan = "Tap to select a diet plan"
        static let managePlans = "Manage Plans"
        static let mealsPerDay = "meals/day"
        static let allPlans = "All Plans"
        static let remaining = "Remaining"
        static let addMeals = "Add Meals"
        static let mealReminders = "Reminders"
        static let trackAdherence = "Track"
        static let reachGoals = "Goals"
        static let linkingMeal = "Linking meal..."
        static let mealLogged = "Meal Logged"
        static let mealLoggedDetails = "%@ • %d cal"
    }
    
    // MARK: - Profile
    struct Profile {
        static let title = "Profile"
        static let preferences = "Preferences"
        static let settings = "Settings"
        static let language = "Language"
        static let selectLanguage = "Select Language"
        static let account = "Account"
        static let appearanceNotificationsBehavior = "Appearance, notifications & behavior"
        static let goalsTracking = "Goals & Tracking"
        static let nutritionGoals = "Nutrition Goals"
        static let appearanceCalorieTrackingNotifications = "Appearance, calorie tracking, and notifications"
        static let support = "Support"
        static let contactSupport = "Contact Support"
        static let rateUs = "Rate Us"
        static let rateUsDescription = "If you're enjoying CalorieVisionAI, please take a moment to rate us on the App Store. Your feedback helps us improve!"
        static let rateOnAppStore = "Rate on App Store"
        static let sendFeedback = "Send Feedback"
        static let feedbackDescription = "Your Feedback"
        static let feedbackFooter = "We'd love to hear your thoughts, suggestions, or report any issues you've encountered."
        static let feedbackSubject = "CalorieVisionAI Feedback"
        static let mailNotConfigured = "Mail is not configured on this device. Please configure Mail in Settings or send feedback to feedback@calai.app"
        static let feedbackSent = "Thank you! Your feedback has been sent successfully."
        static let feedbackFailed = "Failed to send feedback. Please try again later."
        static let termsOfService = "Terms of Service"
        static let privacyPolicy = "Privacy Policy"
        static let version = "Version 1.0.0"
        static let nutritionGoalsSummary = "%d cal | %dg protein"
        static let setUsername = "Set username"
        static let tapToSetName = "Tap to set name"
        static let userId = "User ID"
        static let appVersion = "App Version"
        static let platform = "Platform"
        static let ios = "iOS"
        static let iosVersion = "iOS Version"
        static let device = "Device"
        static let debug = "Debug"
        static let overrideSubscription = "Override Subscription"
        static let manuallyControlSubscription = "Manually control subscription status for testing"
        static let debugIsSubscribed = "Debug: Is Subscribed"
        static let overrideSubscriptionStatus = "Override subscription status"
        static let debugStatus = "Debug Status"
        static let sdkStatus = "SDK Status"
        static let premium = "Premium"
        static let free = "Free"
        static let shareEarnRewards = "Share & earn rewards"
        static let downloadDataAsPDF = "Download your data as PDF"
        static let exportData = "Export Data"
        static let weightData = "Weight Data"
        static let nutritionData = "Nutrition Data"
        static let exportWeightDescription = "Export your weight tracking history as a PDF file."
        static let exportNutritionDescription = "Export your meal logs and nutrition data as PDF files."
        static let exportAllDescription = "Export all your data in a comprehensive PDF report."
        static let generatingPDF = "Generating PDF..."
        static let exportError = "Export Error"
        static let unknownError = "An unknown error occurred."
        static let weightHistory = "Weight History"
        static let mealHistory = "Meal History"
        static let dailyNutritionSummary = "Daily Nutrition Summary"
        static let aggregatedDailyTotals = "Aggregated daily totals"
        static let exportAllData = "Export All Data"
        static let completeDataBackup = "Complete data backup"
        static let units = "Units"
        static let weightUnits = "Weight Units"
        static let metricUnits = "Kilograms (kg)"
        static let imperialUnits = "Pounds (lbs)"
        static let noWeightEntriesYet = "No weight entries yet"
        static let startTrackingWeight = "Start tracking your weight to see your progress here"
        static let addFirstEntry = "Add First Entry"
        static let progress = "Progress"
        static let totalChange = "Total Change"
        static let average = "Average"
        static let entries = "entries"
        static let allEntries = "All Entries"
        static let noteOptional = "Note (optional)"
        static let saveWeight = "Save Weight"
        static let choosePreferredAppearance = "Choose your preferred appearance"
        static let appearance = "Appearance"
        static let calorieTracking = "Calorie Tracking"
        static let notificationsDisplay = "Notifications & Display"
        static let addBurnedCalories = "Add Burned Calories"
        static let addBurnedCaloriesDescription = "Add calories burned from exercise back to your daily goal. Great for maintaining energy during active days."
        static let rolloverCalories = "Rollover Calories"
        static let rolloverCaloriesDescription = "Carry up to 200 unused calories from yesterday into today's goal."
        static let autoAdjustMacros = "Auto-Adjust Macros"
        static let autoAdjustMacrosDescription = "Automatically adjust protein, carbs, and fat when you change your calorie goal."
        static let badgeCelebrations = "Badge Celebrations"
        static let badgeCelebrationsDescription = "Show a full-screen animation when you unlock a new achievement badge."
        static let liveActivity = "Live Activity"
        static let liveActivityDescription = "Show your daily calories and macros on your Lock Screen and Dynamic Island."
        static let system = "System"
        static let light = "Light"
        static let dark = "Dark"
        static let calorieGoal = "Calorie Goal"
        static let caloriesPerDay = "calories per day"
        static let proteinGoal = "Protein Goal"
        static let carbsGoal = "Carbs Goal"
        static let fatGoal = "Fat Goal"
        static let dailyGoals = "Daily Goals"
        static let macroBreakdown = "Macro Breakdown"
        static let youCanChangeThisAnytime = "You can change this anytime in Settings"
        static let basedOnProfileAndGoals = "Based on your profile and goals"
        static let calculatesOptimalMacros = "Calculates optimal macros based on your profile and current calorie goal"
        static let recommended = "Recommended"
        static let recommendedCalories = "Recommended: %d cal"
        static let perDay = "per day"
        static let myBadges = "My Badges"
        static let badgesEarned = "Badges Earned"
        static let badgesEarnedCount = "%d of %d earned"
        static let progressComplete = "%d%% Complete"
        static let congratulationsAllBadges = "Congratulations! You've earned all badges!"
        static let keepLoggingToUnlock = "Keep logging to unlock more badges!"
        static let allBadges = "All Badges"
        static let earned = "Earned"
        static let earnedFormat = "Earned %@"
        static let of = "of"
        static let personalDetails = "Personal Details"
        static let editName = "Edit Name"
        static let bmi = "BMI"
        static let category = "Category"
        static let progressToGoal = "Progress to Goal"
        static let currentWeight = "Current Weight"
        static let goalWeight = "Goal Weight"
        static let feet = "Feet"
        static let inches = "Inches"
        static let height = "Height"
        static let dateOfBirth = "Date of Birth"
        static let gender = "Gender"
        static let dailyStepGoal = "Daily Step Goal"
        static let username = "Username"
        static let yourUsernameWillBeDisplayed = "Your username will be displayed as @%@"
        static let editUsername = "Edit Username"
        static let referralCode = "Referral Code"
        static let yourReferralCodeCopied = "Your referral code has been copied to clipboard."
        static let friendCodeApplied = "Friend's referral code has been applied successfully."
        static let inviteFriendsEarnRewards = "Invite Friends & Earn Rewards"
        static let shareUniqueCode = "Share your unique code with friends and both of you will receive special benefits!"
        static let yourReferralCode = "Your Referral Code"
        static let copy = "Copy"
        static let share = "Share"
        static let haveFriendsCode = "Have a Friend's Code?"
        static let applyCode = "Apply Code"
        static let appliedCode = "Applied Code"
        static let codeAppliedSuccessfully = "Code applied successfully"
        static let howItWorks = "How It Works"
        static let ringColorsExplained = "Ring Colors Explained"
        static let ringColorsDescription = "On the homepage calendar, the colored rings around each date show how close you were to your daily calorie goal:"
        static let green = "Green"
        static let upTo100CaloriesOver = "Up to 100 calories over your deficit target"
        static let yellow = "Yellow"
        static let calories100To200Over = "100-200 calories over your goal"
        static let red = "Red"
        static let moreThan200CaloriesOver = "More than 200 calories over your goal"
        static let dotted = "Dotted"
        static let noMealsLoggedThatDay = "No meals logged that day"
        static let supportRequest = "Support Request"
        static let copiedToClipboard = "Copied!"
        static let emailContentCopied = "Email content has been copied. Please paste it into your email app."
        static let to = "To:"
        static let from = "From:"
        static let subject = "Subject:"
        static let pleaseDescribeIssue = "Please describe your issue:"
        static let debugInformation = "Debug Information"
        static let debugInfoHelpsDiagnose = "This information helps us diagnose issues faster."
        static let changeProfilePhoto = "Change Profile Photo"
        static let removePhoto = "Remove Photo"
        static let bodyMetrics = "Body Metrics"
        static let weightGoal = "Weight Goal"
        static let activity = "Activity"
    }
    
    // MARK: - Weight
    struct Weight {
        static let saveWeight = "Save Your Weight"
        static let trackProgress = "Track your progress by saving your current weight"
        static let weight = "Weight"
        static let currentWeight = "Current Weight"
        static let targetWeight = "Target Weight"
        static let startWeight = "Start Weight"
        static let goalWeight = "Goal Weight"
        static let lastLogged = "Last"
        static let noWeightLogged = "No weight logged"
    }
    
    // MARK: - Premium
    struct Premium {
        static let premiumRequired = "Premium Required"
        static let upgradeToUnlock = "Upgrade to unlock"
        static let areYouSure = "Are you sure you want to skip the free trial?"
        static let claimFreeTrial = "Claim your free trial now without paying"
        static let startFreeTrial = "Start Free Trial"
        static let skipFreeTrial = "Skip free trial"
        static let notNow = "Not now"
        static let premiumFeature = "Premium feature"
        static let premium = "Premium"
        static let upgradeToPremium = "Upgrade to Premium"
    }
    
    // MARK: - History
    struct History {
        static let title = "History"
        static let noHistoryYet = "No History Yet"
        static let historyDescription = "Your meal history will appear here\nonce you start tracking"
        static let noResults = "No Results"
        static let noEntriesFound = "No entries found for the selected time period"
        static let clearFilters = "Clear Filters"
        static let loadingHistory = "Loading history..."
        static let noEntriesFoundForSearch = "No entries found for \"%@\""
        static let searchByDateDayMonth = "Search by date, day, or month"
        static let createYourDietPlan = "Create Your Diet Plan"
        static let unlockDietPlans = "Unlock Diet Plans"
        static let scheduleRepetitiveMeals = "Schedule repetitive meals and track adherence"
        static let subscribeToCreateDietPlans = "Subscribe to create diet plans with scheduled meals"
        static let createDietPlan = "Create Diet Plan"
        static let subscribeCreate = "Subscribe & Create"
        static let completed = "Completed"
        static let missed = "Missed"
        static let scheduled = "Scheduled"
        static let deleteEntry = "Delete Entry"
        static let deleteExerciseQuestion = "Delete %@ exercise? This cannot be undone."
        static let deleteMealQuestion = "Delete \"%@\"? This cannot be undone."
        static let consumed = "Consumed"
        static let burned = "Burned"
        static let net = "Net"
        static let meals = "meals"
        static let exercises = "exercises"
        static let loadingLogs = "Loading logs..."
        static let noLogsYet = "No Logs Yet"
        static let startLoggingMeals = "Start logging your meals and exercises to see them here"
        static let mealDetails = "Meal Details"
        static let loadingMealDetails = "Loading meal details..."
        static let unableToLoadMealDetails = "Unable to load meal details"
        static let calories = "calories"
        static let nutritionBreakdown = "Nutrition Breakdown"
        static let loadingMeals = "Loading meals..."
        static let noMeals = "No Meals"
        static let noMealsRecorded = "No meals were recorded for this day"
        static let totalCalories = "total calories"
        static let mealsCapitalized = "Meals"
        static let meal = "meal"
        static let mealsPlural = "meals"
        static let mealNotFound = "Meal Not Found"
        static let items = "items"
        static let caloriesLabel = "calories"
    }
    
    // MARK: - Onboarding
    struct Onboarding {
        static let allowTracking = "Allow Tracking"
        static let welcome = "Welcome"
        static let getStarted = "Get Started"
        static let skip = "Skip"
        static let back = "Back"
        static let welcomeToCalorieVisionAI = "Welcome to CalorieVisionAI"
        static let whatIsYourGender = "What is your gender?"
        static let howOldAreYou = "How old are you?"
        static let bodyMetrics = "Body Metrics"
        static let weightGoal = "Weight Goal"
        static let goalWeight = "Goal Weight"
        static let activity = "Activity"
        static let changeAnytimeInSettings = "You can change this anytime in Settings."
        static let allowNotifications = "Allow Notifications"
        static let notNow = "Not Now"
        static let enableNotifications = "Enable Notifications"
        static let missingInputDefinition = "Missing input definition."
        static let chooseOne = "Choose one"
        static let onboardingError = "Onboarding Error"
        static let enabled = "Enabled"
    }
    
    // MARK: - Errors
    struct Errors {
        static let somethingWentWrong = "Something went wrong"
        static let tryAgain = "Try Again"
        static let noFoodDetected = "No Food Detected"
        static let cameraError = "Camera Error"
        static let permissionDenied = "Permission Denied"
    }
    
    // MARK: - Notifications
    struct Notifications {
        static let timeToLogWeight = "Time to Log Your Weight"
        static let trackProgress = "Track your progress by logging your weight this morning."
    }
    
    // MARK: - Goals
    struct Goals {
        static let dailyCalories = "Daily Calories"
    }
    
    // MARK: - Goals Generation
    struct GoalsGeneration {
        static let generatingYourPlan = "Generating Your Plan"
        static let yourPersonalizedGoals = "Your Personalized Goals"
        static let basedOnProfile = "Based on your profile and objectives"
    }
    
    // MARK: - Scanning
    struct Scanning {
        static let analyzingYourMeal = "Analyzing your meal..."
        static let aiProcessing = "AI is processing your food image"
        static let scanMeal = "Scan Meal"
        static let captureYourMeal = "Capture Your Meal"
        static let takePhotoOrChoose = "Take a photo or choose from your library"
        static let takePhoto = "Take Photo"
        static let chooseFromLibrary = "Choose from Library"
        static let scanning = "Scanning..."
        static let addNoteOptional = "Add a note (optional)"
        static let describeFoodForAccuracy = "Describe the food to help improve analysis accuracy."
        static let analyze = "Analyze"
        static let alignDocument = "Align document within frame"
        static let confirm = "Confirm"
        static let retake = "Retake"
        static let analyzeMeal = "Analyze Meal"
        static let noFoodInImage = "We couldn't identify any food in this image."
        static let tipsForBetterResults = "Tips for better results"
        static let calAI = "CalorieVisionAI"
        static let tryAgain = "Try Again"
        static let takeNewPhoto = "Take New Photo"
        static let ohNo = "Oh no!"
        static let enableCameraPermissions = "In order to scan your food, you must enable camera permissions"
        static let openSettings = "Open settings"
        static let freeScansLeft = "3 free scans left"
        static let cameraRequiresPhysicalDevice = "Camera requires physical device"
        static let weCantSeeYourCamera = "We can't see your camera"
        static let skip = "Skip"
        static let identifyingIngredients = "Identifying ingredients..."
        static let calculatingPortionSizes = "Calculating portion sizes..."
        static let estimatingNutritionalValues = "Estimating nutritional values..."
        static let analyzingMacros = "Analyzing macros..."
    }
    
    // MARK: - Results
    struct Results {
        static let analysisResults = "Analysis Results"
        static let fixResult = "Fix Result"
        static let whatIsThisFood = "What is this food?"
        static let describeFoodForAnalysis = "Describe the food to help us analyze it more accurately."
        static let foodExamplePlaceholder = "e.g., Homemade chicken caesar salad"
        static let beSpecificAboutIngredients = "Be specific about ingredients, portion sizes, or cooking methods if possible."
        static let reAnalyze = "Re-analyze"
        static let ingredients = "Ingredients"
        static let totalNutrition = "Total Nutrition"
        static let notes = "Notes"
        static let highConfidence = "High Confidence"
        static let mediumConfidence = "Medium Confidence"
        static let lowConfidence = "Low Confidence"
    }
    
    // MARK: - Authentication
    struct Authentication {
        static let calorieVisionAI = "CalorieVisionAI"
        static let trackNutritionWithEase = "Track your nutrition with ease"
        static let getStarted = "Get Started"
    }
    
    // MARK: - Main
    struct Main {
        static let noInternetConnection = "No Internet Connection"
        static let home = "Home"
        static let progress = "Progress"
        static let profile = "Profile"
    }
    
    // MARK: - Content
    struct Content {
        static let loading = "Loading..."
    }
    
    // MARK: - Badge
    struct Badge {
        static let badgeEarned = "Badge Earned!"
        static let firstBite = "First Bite"
        static let weekWarrior = "Week Warrior"
        static let goalGetter = "Goal Getter"
        static let gettingStarted = "Getting Started"
        static let consistentLogger = "Consistent Logger"
        static let dedicatedTracker = "Dedicated Tracker"
        static let centurion = "Centurion"
        static let activeStart = "Active Start"
        static let perfectWeek = "Perfect Week"
        static let proteinChampion = "Protein Champion"
        static let locked = "Locked"
    }
}

// MARK: - Localized String Access

extension AppStrings {
    /// Get a localized string by key
    /// Usage: AppStrings.localized(.Home.title)
    static func localized(_ key: String) -> String {
        return LocalizationManager.shared.localizedString(for: key)
    }
    
    /// Get a localized string with comment
    static func localized(_ key: String, comment: String) -> String {
        return LocalizationManager.shared.localizedString(for: key, comment: comment)
    }
    
    /// Get a localized string with format arguments
    static func localized(_ key: String, arguments: CVarArg..., comment: String = "") -> String {
        let format = LocalizationManager.shared.localizedString(for: key, comment: comment)
        return String(format: format, arguments: arguments)
    }
}

